=== CroixDuSud/Autom/MODULE 1/XML-XPATH/Exo stagiaire/exo dtd/Exercice 1/cybershoppe_ARA.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cyberSh (produit)*>

<!ELEMENT produit (nom, descrip, prix, quanti)>

<!ELEMENT nom (#PCDATA) >
<!ELEMENT descrip (#PCDATA) >
<!ELEMENT prix (#PCDATA) >
<!ELEMENT quanti (#PCDATA) >

<!ATTLIST produit 
	cat (jouet | livre) #REQUIRED
	id ID #REQUIRED >

=== CroixDuSud/Autom/MODULE 1/XML-XPATH/Exo stagiaire/exo dtd/Exercice 1/cybershoppe_ARA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cyberSh SYSTEM "cybershoppe_ARA.dtd" >

<cyberSh>
	<produit cat="jouet" id="id0">
		<nom>Playmobil</nom>
		<descrip>En avant les histoires !</descrip>
		<prix>7,99</prix>
		<quanti>100</quanti>
	</produit>

	<produit cat="livre" id="id1">
		<nom>Le petit prince</nom>
		<descrip>Un classique incontournable</descrip>
		<prix>9,99</prix>
		<quanti>50</quanti>
	</produit>

</cyberSh>
